# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  #tomcat启动的端口
  port: 8081
  connection-timeout: 5000
  servlet:
    #tomcat访问路径，类似tomcat/webapps下的项目名称
    context-path: /jwt

spring:
  application:
    name: springbt-shiro-jwt

  boot:
    admin:
      client:
        url: http://localhost:8080  #添加到应用监控
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
    view:
      prefix: classpath:/templates/
      suffix: .html
  resources:
    add-mappings: false
  main:
    allow-bean-definition-overriding: true

  datasource:
    name: ShiroJwt
    url: jdbc:mysql://127.0.0.1:3306/shirojwt?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20


shiro:
  loginUrl: "xxx"  #认证不通过的页面
  UnauthorizedUrl: "xxx"  #授权不通过的跳转页面

encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==  # AES密码加密私钥(Base64加密)
encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==  # JWT认证加密私钥(Base64加密)
accessTokenExpireTime: 3000  # AccessToken过期时间-5分钟-5*60(秒为单位)

mybatis:
  # Mybatis配置Mapper路径
  mapper-locations: classpath:mapper/*.xml
  # Mybatis配置Model类对应
  type-aliases-package: com.keelin.model

#添加到监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

