server:
  port: 8806   # 服务端口号
spring:
  application:
    name: feignclient     # 服务名称
  security:
    basic:
      enabled: true
    user:
      name: keelin
      password: ${REGISTRY_SERVER_PASSWORD:keelin}
eureka:
  client:
    serviceUrl:
      defaultZone: http://keelin:keelin@localhost:8881/eureka/   # 注册到的eureka服务地址
feign:
  hystrix:
    enabled: true
