server:
  port: 8805   # 服务端口号
spring:
  application:
    name: ribbonclient     # 服务名称
  security:
    basic:
      enabled: true
    user:
      name: keelin
      password: ${REGISTRY_SERVER_PASSWORD:keelin}
eureka:
  client:
    serviceUrl:
      defaultZone: http://keelin:keelin@localhost:8881/eureka/   # 注册到的eureka服务地址
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: keelin
      user.password: keelin
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS